### PR TITLE
Update ruRU locale

### PR DESCRIPTION
**Pull request by KasVital**
wantBattleDefStance, wantBattleBerserkStance, wantBerserkerStance, wantDefensiveStance and wantBattleStance
fix last time, sry)

### CODE REVIEW

**Comment by shagu** [comment]
I did a quick test and none of the automatic stance changes works with this commit.

**Comment by KasVital** [comment]
You used ruRU client wow from vk.com/wowruru?

**Comment by KasVital** [comment]
Ups

**Comment by KasVital** [comment]
i checked this before commit

**Comment by shagu** [comment]
Client: 

Unhandled Stance: 

Got that client from elysium-wow download section.

**Comment by KasVital** [comment]
i use it on Elysium it support ruRU client and i can use /cast Боевая стойка , you not)

**Comment by KasVital** [comment]
u can change first line for sec pfLocaleShift["ruRU"] = {
['BattleStance'] = "Battle Stance", ...
then it work at your server

**Comment by shagu** [comment]
It seems like you don't got the point what this translation is all about:
It is used to automatically switch to the required stance as soon a Spell requires you to switch.
This is done by reading the Error Message and then automatically cast the stance which is required for your spell.

These error messages are Client side and have to be translated correctly, 
otherwise you won't be able to automatically change from "Defense Stance" to "Battle Stance" 
when using "Charge". (Shown in the Screenshot)

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/c1e1ac4f728b3a3b2b53d817e94e8e5f2a930483
Again, added the periods on the line end and it worked on my tests.

**Comment by KasVital** [comment]
image

**Comment by KasVital** [comment]
image
latest version

**Comment by KasVital** [comment]
https://www.youtube.com/watch?v=ZGsXSo0xxNA&feature=youtu.be
i used my version without "." and didnt work with "."

**Comment by shagu** [comment]
Strange... Which gameversion do you have? (shown in the login screen)

**Comment by KasVital** [comment]
rofl 
image

**Comment by shagu** [comment]
I can't understand any word, but yours looks different

**Comment by KasVital** [comment]
May be other version i dont know..

вт, 27 дек. 2016 г., 19:54 shagu <notifications@github.com>:

**Pull request closed without merging**
