### PR TITLE
gui: add auto-resize of top tabs and Updating ruRU localization

### PR DESCRIPTION
**Pull request by Lichery**
bandicam 2017-11-16 01-05-55-235
bandicam 2017-11-16 01-06-17-243

### CODE REVIEW

**Comment by Lichery** [comment]
gui: add auto-resize of top tabs
fix #677 many thanks @Shuraken007

Forgive me, that here everything is in a pile... I again can not do it separately...
Also, the commit e77333f is superfluous, I updated addon to your version and he also attached himself here ... :(

**Comment by Lichery** [comment]
Also can still add the minimum width for the buttons so that they are not too narrow if there are few characters in the title.

**Comment by Lichery** [comment]
hurray, corrected the conflict ... it is strange that the first time was not corrected ...
I'm sorry that everything looks so awful ... If you are entangled, I can close and remake PR

**Comment by shagu** [comment]
I just made it slightly different without the `QuestLogDummyText`-hack: https://github.com/shagu/pfUI/commit/69c9efc6ebf8f203216404712ce5706f3adda430

Thanks for this PR :)

**Pull request closed without merging**
