### PR TITLE
Actionbar: Action on button down (toggle)

### PR DESCRIPTION
**Pull request by Sour**
Can enable/disable in settings.
#656

### CODE REVIEW

**Comment by shagu** [comment]
I'm sorry of the delay. I am aware of this PR but like to have some detailled testing on that. Right now, I'm very busy with all the other addons and holding this back. Please be patient, Thank you :)

**Comment by rhnorskov** [comment]
I have been doing some testing, and it seems to working great, with the exception of `Auto Attack` and `Auto Shot`. If a keybind for any of the two abilities is pressed an `Interrupted` error will be thrown. Maybe an exception needs to be added to these two abilities.

**Comment by shagu** [comment]
This should do the same, or am I missing something?
```
  if C.bars.keydown == "1" then
    hooksecurefunc("ActionButtonDown", function(id)
      ActionButtonUp(id)
    end, true)
  end
```

**Comment by shagu** [comment]
It also seems like, your solution does only work for the main actionbar, I've added another hook for the MultiActionBar:

```
  if C.bars.keydown == "1" then
    hooksecurefunc("ActionButtonDown", function(id)
      ActionButtonUp(id)
    end, true)

    hooksecurefunc("MultiActionButtonDown", function(bar, id)
      MultiActionButtonUp(bar, id)
    end, true)
  end
```

**Comment by shagu** [comment]
https://github.com/shagu/pfUI/commit/6f7f8a18b485e1604921e1f3657d08c9a05214e6

**Pull request closed without merging**
