### PR TITLE
Fix for errors w/ late version of SuperMacro

### PR DESCRIPTION
**Pull request by laytya**
did u forget to pass actionID to SM_ActionButton_SetTooltip?

### CODE REVIEW

**Comment by shagu** [comment]
I don't see why this is required. `SM_ActionButton_SetTooltip` does not take any arguments.
https://github.com/Monteo/SuperMacro/blob/master/SM_Tooltip.lua#L28
https://github.com/laytya/SuperMacro/blob/master/SM_Tooltip.lua#L28

**Comment by laytya** [comment]
Ah I see... its old repository. of Super Macro  - Ill delete it.
See at https://github.com/laytya/SuperMacro-vanilla

**Comment by shagu** [comment]
> did u forget to pass actionID

You broke it this year on your own fork and ask me, if I forgot to add it 3 years ago when the thirdparty integration was made? You could have at least linked the only version around that is affected by this PR.

I wonder why this is required now for your fork and what's the benefit of your new one to original.
Also, do you need to fork all actionbars now to build SM support into those (Discord, modui, zbar, ..)?

I'm not sure if this works at all. The `ActionButton_GetPagedID(button)` function requires a `.isBonus` attribute to work, which is not set on the pfUI actionbar buttons. Have you tested this change to be functional and not breaking things?

**Comment by laytya** [comment]
Yes i tested it. It works well.
About this fork - i just miss my old one. =)
This changes in SM - just compatibility fixes for TheoryCraft work on macros. It was not worked before.
Also some support of some ActionBars addons like DAB, Bongos,   i also tested w/ pfUI. zBar and modui didnt tested.

**Comment by laytya** [comment]
> > did u forget to pass actionID
> 
> You broke it this year on your own fork and ask me, if I forgot to add it 3 years ago when the thirdparty integration was made? You could have at least linked the only version around that is affected by this PR.

Sorry, may bad.

**Comment by laytya** [comment]
zbar working well also

**Comment by shagu** [comment]
Perfect, thank you :)
I have merged it by this commit: https://github.com/shagu/pfUI/commit/f0d1abef9c62b81644a36670afa5edb9eadddcbc

**Pull request closed without merging**
