### PR TITLE
additional translation ruRU

### PR DESCRIPTION
**Pull request by KasVital**

### CODE REVIEW

**Comment by shagu** [comment]
Awesome! Thanks alot mate. What do you mean by "check" and "checkcheck" ? Should I better wait before merging?

**Comment by KasVital** [comment]
I think u can merge it, i checked it, but not all of spellevents..

**Comment by KasVital** [comment]
coz i dont know how addon use it %2$s %1$s %3$s etc

**Comment by shagu** [comment]
Could you please check the Warrior stances again? 
I tried out and they didn't work. 
Sadly I don't understand any word and can't copy this kind of characters by hand.




Thanks in advance

**Comment by shagu** [comment]
I modified your commits an pushed into master. Thanks for your effort =)
https://github.com/shagu/pfUI/commit/9a6096089d88f44eca5e54ff79640a778fba94ec

**Pull request closed without merging**
